version: '3.8'
services:
  frontend:
    container_name: fe
    restart: unless-stopped
    build:
      context: ./apps/FE
      dockerfile: Dockerfile
    # ports:
    #   - "3000:3000"
    volumes:
      - ./apps/FE:/usr/src/app
    depends_on:
      # - backend
      - apache
    networks:
      - default-web-server

  apache:
    container_name: apache
    build:
      context: ./apache
      dockerfile: Dockerfile
    volumes:
      - ./apache/httpd.conf:/etc/apache2/httpd.conf
      - ./apache/deafult.conf:/etc/apache2/sites-available/000-default.conf
      - ./apps:/usr/local/apache2/htdocs
      - ./html:/var/www/html
    ports:
      - 80:8080
      - 8080:8080
      - 100:100
      - 2000:2000
    restart: unless-stopped
    networks:
      - default-web-server

networks:
  default-web-server:
    driver: bridge