version: '3.8'
services:
  frontend:
    container_name: fe
    restart: unless-stopped
    build:
      context: ./apps/FE
      dockerfile: Dockerfile
    # ports:
    #   - "3000:3000"
    volumes:
      - ./apps/FE:/usr/src/app
    depends_on:
      # - backend
      - apache
    networks:
      - default-web-server

  # nginx:
  #   container_name: web-server
  #   restart: unless-stopped
    # build:
    #   context: ./nginx
    #   dockerfile: Dockerfile
  #   ports:
  #     - 80:80
  #     - 3000:3000
    # volumes:
    #   - ./:/var/www
    #   - ./nginx:/etc/conf.d/
    # networks:
    #   - default-web-server

  apache:
    container_name: apache
    build:
      context: ./apache
      dockerfile: Dockerfile
    volumes:
      - ./apache/deafult.conf:/usr/local/apache2/conf/default.conf
      - ./apps:/usr/local/apache2/htdocs
    ports:
      - 8080:80
    restart: unless-stopped
    networks:
      - default-web-server

networks:
  default-web-server:
    driver: bridge