version: '3.8'
services:
  frontend:
    container_name: fe
    restart: unless-stopped
    build:
      context: ./FE
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./FE:/usr/src/app
    depends_on:
      # - backend
      - nginx
    networks:
      - default-web-server

  nginx:
    container_name: web-server
    restart: unless-stopped
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./nginx:/etc/conf.d/
    networks:
      - default-web-server

networks:
  default-web-server:
    driver: bridge